### ISSUE TITLE
Index support for new crawler page format

### ISSUE THREAD

**Issue by SandMV** [solariq/sensearch#25]
Нужно протащить в страницу индекса информацию о категориях, секциях и ссылках

**Comment by tehnar** [comment]
И ссылках!

**Comment by SandMV** [comment]
@tehnar @atem11 Сейчас краулер возвращает id страницы, на которую делается ссылка. А можно туда ещё протащить URI или это сложно сделать?

**Comment by SandMV** [comment]
DONE
