### ISSUE TITLE
A lot of GloVe vectors are missing!

### ISSUE THREAD

**Issue by SandMV** [solariq/sensearch#26]
После запуска тестов оказалось, что для большого количества слов не были найдены векторы. Вот лог: https://bpaste.net/show/fffca7614bf8
Возможно, проблема только в тестах, нужно проверить, не теряем ли мы слова, когда строим GloVe

**Comment by tehnar** [comment]
Вроде сейчас работает. Небольшое количество слов все равно не найдено, потом и это полечим
