### ISSUE TITLE
Data structures for embeddings

### ISSUE THREAD

**Issue by tehnar** [solariq/sensearch#7]
Эмбеддинги жрут слишком много оперативки => хотим хранить на диске и подгружать по мере необходимости.

Для начала можно заюзать какой-нибудь LRU-cache, чтобы в оперативке лежали только недавно использованные вектора.
Нужно еще понять, как эффективно хранить вектора (в одном файлике на диске -- не вариант). Один из возможных способов Игорь скидывал в чатик.

**Comment by teremax** [comment]
Выполнено, но нужно MapDB поменять на LevelDB
